<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm PIN_confirm_pin</name>
   <tag></tag>
   <elementGuidId>8d16a0bd-4135-4043-8ce4-af57f88fdd98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm_pin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_pin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8336d8f0-591f-4ad3-9546-c5b783bff3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ae6ae4df-cc3d-48b9-a738-a48d1842f9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ebef4ad-a7ba-4a97-a259-07590c8464e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control english_onlyrop_ref</value>
      <webElementGuid>9616f76a-264e-453a-9052-e710d69040da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_pin</value>
      <webElementGuid>6a3e26d9-7145-491d-bfbe-ee98e0977250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>confirm pin</value>
      <webElementGuid>cd9b2996-5221-4e92-a6f6-7f88245081df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_pin&quot;)</value>
      <webElementGuid>9905fd3a-f8d2-4802-8e2e-b91cadf44c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_pin']</value>
      <webElementGuid>befbed7b-c79f-43fd-a126-c4165c0ca603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credentials_form']/div/div[2]/input</value>
      <webElementGuid>bbeab6fb-c1b8-44a8-8290-462dccf896c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div[2]/input</value>
      <webElementGuid>54da9fb1-c35b-42a6-9c65-f6a792dc751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'textbox' and @id = 'confirm_pin' and @title = 'confirm pin']</value>
      <webElementGuid>10efd8d3-8c8f-4d68-bb3f-cc45b8935840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
