<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PIN_pin</name>
   <tag></tag>
   <elementGuidId>5f7a891d-0d1e-4b32-a150-6379c9ffe803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26932bfb-2209-4d8c-8262-1b031b9d7d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>297ac6fa-b3c4-4cb6-9a15-8358f666eaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>646f5cd0-203b-47ae-b192-bdf988430b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control english_only</value>
      <webElementGuid>8a4a4ffa-2e5a-444e-9d7e-ff959450cf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin</value>
      <webElementGuid>152ea5fa-2d1a-41a5-9a9a-490d2fff5974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>pin</value>
      <webElementGuid>4b70f1b3-a993-44e0-bfac-c12e98556f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin&quot;)</value>
      <webElementGuid>fb0fc5d3-aaa8-420d-8580-11efba81cb85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pin']</value>
      <webElementGuid>2ebd6c31-f28a-4a13-9e03-b32dda7089fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credentials_form']/div/div/input</value>
      <webElementGuid>e85456dd-d8dc-4774-a5d8-326da9581ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div/input</value>
      <webElementGuid>d4d7e19d-c603-403f-be37-a29f119fecf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'textbox' and @id = 'pin' and @title = 'pin']</value>
      <webElementGuid>1e9df17a-7bfd-4bf0-85c5-3a74c49d1ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
