<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>b8fb7726-bbe9-43d7-95f5-6d1b10f732a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>290ed8b2-e78b-4aa5-85ee-102656755ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0)</value>
      <webElementGuid>eb34e815-0a8e-4630-bd36-e14358512129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-theme-03 btn-block</value>
      <webElementGuid>22937ae9-6b9c-45d8-af4e-57c0c0255742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_next</value>
      <webElementGuid>1877044d-7d84-43cb-88c4-0027c0a68034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Next
                          </value>
      <webElementGuid>353de002-afc3-43b0-9b53-f5d4f075e550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_next&quot;)</value>
      <webElementGuid>edb74840-d264-4059-afcc-1870f4baecba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_next']</value>
      <webElementGuid>75823ac9-64b0-4e74-bee2-23c71e4568f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rop-app']/div/div/div/div[3]/ul/li[2]/a</value>
      <webElementGuid>f0405690-8b13-4f4e-8351-95c498952145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::a[1]</value>
      <webElementGuid>dc8773cd-e2ae-41e6-9093-9a98f4f7cfe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension :'])[2]/following::a[2]</value>
      <webElementGuid>b6e27db9-cff9-4a16-9291-bf4fa99631de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Links'])[1]/preceding::a[2]</value>
      <webElementGuid>01c3a734-4eed-46a0-a640-d527532d1fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript: void(0)')]</value>
      <webElementGuid>3e8fb429-590e-4f27-956d-f993056b50fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[2]/a</value>
      <webElementGuid>91791c09-b3a6-4739-9833-5111495085de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript: void(0)' and @id = 'btn_next' and (text() = '
                            Next
                          ' or . = '
                            Next
                          ')]</value>
      <webElementGuid>241c802b-11b8-4f6b-b013-2efbe19903ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
