<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I agree to receive News, and promotio_6d6b5d</name>
   <tag></tag>
   <elementGuidId>b74cd5f3-c8f6-4fb7-b5e0-a5f84efeb3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;delivery&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='delivery']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ca3509e-e43b-440f-9f75-5bd920e69d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fefab4b4-cb03-4a48-b114-fdfdf97cdd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ST</value>
      <webElementGuid>c5cb4fa3-cfbd-4a00-9211-c9b340b866c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delivery</value>
      <webElementGuid>0473796e-9042-4bbf-bbf8-46d9e2b9ecf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery</value>
      <webElementGuid>51cdd929-324e-4b54-9b0d-ba5f2957945e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>I agree to receive News, and promotional offers from Royal Orchid Plus and THAI</value>
      <webElementGuid>cfbbb4d6-b99c-43f4-b55b-93d8349fc3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_info_form&quot;)/div[@class=&quot;row&quot;]/div[2]/input[@class=&quot;delivery&quot;]</value>
      <webElementGuid>dc143e2c-2a35-40a4-a012-3c72b345cd64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='delivery']</value>
      <webElementGuid>689a91eb-d6bb-42da-9f56-e84331a4ac9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='email_info_form']/div[2]/div[2]/input</value>
      <webElementGuid>245df556-cd2f-4bb6-9de0-ed998a72b2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div[2]/div[2]/input</value>
      <webElementGuid>5b52c658-38a1-4713-9bfc-7628efbc8431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'delivery' and @title = 'I agree to receive News, and promotional offers from Royal Orchid Plus and THAI']</value>
      <webElementGuid>1e496faa-1b13-44d2-b90e-ff1076fdd17c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
