<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm PIN_confirm_pin</name>
   <tag></tag>
   <elementGuidId>ab5d7a91-c165-4eb9-b7bf-2042f687ee3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm_pin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_pin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb0fef43-d3cb-4252-b4ee-eea2f330043e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>94e490c7-6321-4c4c-861b-863e30cf7a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>981291bc-e0c7-4d93-b099-732c7a9e2bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control english_onlyrop_ref</value>
      <webElementGuid>c5d1d374-caec-4870-9634-3a9645efd95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_pin</value>
      <webElementGuid>a00fa166-905b-49c0-be23-14d5c0ae85d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>confirm pin</value>
      <webElementGuid>977bbc6f-fb94-460d-878f-ff59fcb1d070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_pin&quot;)</value>
      <webElementGuid>213d6c0f-308d-43d2-837a-a6aee3276b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_pin']</value>
      <webElementGuid>4dd02226-be98-4894-888b-2cb90cbd236f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credentials_form']/div/div[2]/input</value>
      <webElementGuid>50c9fe71-fa54-4fd6-84e5-52377458307c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div[2]/input</value>
      <webElementGuid>5bcd6315-0252-4bfc-8060-5ccc66346489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'textbox' and @id = 'confirm_pin' and @title = 'confirm pin']</value>
      <webElementGuid>aa32b42c-d06f-42dd-928d-61218a40e1e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
