<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Home_preferred_address</name>
   <tag></tag>
   <elementGuidId>4a1c1c36-74d6-4a04-b3ea-239e2fe8b54e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add_home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f56cedb4-927f-40bd-8fed-f14b651005fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32b11733-d498-4ce1-8928-0fd03f27ac0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6585a396-58df-4186-b86b-377a48e46c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferred_address</value>
      <webElementGuid>d727b768-d3b7-4b82-9622-a1bc8c4a4ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>891cff65-3c47-4d14-b019-754650e043b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_home</value>
      <webElementGuid>f58c0f07-8190-454a-bc59-8101bd4cf577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_home&quot;)</value>
      <webElementGuid>77a6345a-6e2f-407c-a6fe-f1694614c510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add_home']</value>
      <webElementGuid>3ce8203b-26a5-4a19-be6b-d966627a7d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_details_form']/div/div/label/input</value>
      <webElementGuid>0524b58e-8b64-4bed-a903-f236af39fd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/label/input</value>
      <webElementGuid>36a8074d-fc70-4f90-bdde-bffdd0b13016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'preferred_address' and @id = 'add_home']</value>
      <webElementGuid>29abe843-f6ad-49a3-aa81-9825e149746a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
