<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business_preferred_address</name>
   <tag></tag>
   <elementGuidId>b7bc262a-a340-46b2-b790-2a1705a751d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_business</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add_business']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07bdf108-dc86-4d09-8740-59b5db80f568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>80331a33-e810-4987-99be-6f740206b786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferred_address</value>
      <webElementGuid>2facd808-8df8-4d5a-9238-a7d98605a71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>515c4ef3-342b-4fd3-b982-903a1118f760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_business</value>
      <webElementGuid>5d721f6e-881a-4e0c-a3f9-4a847b508ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_business&quot;)</value>
      <webElementGuid>b8104191-177b-434f-bb05-77e65e27d121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add_business']</value>
      <webElementGuid>500f471b-149a-4c60-bc33-16b0127a6fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_details_form']/div/div/label[2]/input</value>
      <webElementGuid>90f24288-ecf0-4a8b-9f93-05a2e508e86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>7ffc7278-1681-4135-81ce-ebc57f53cc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'preferred_address' and @id = 'add_business']</value>
      <webElementGuid>764b5237-0a2c-4c74-829d-e8f3a1004740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
