<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company NameDepartment_company_name2</name>
   <tag></tag>
   <elementGuidId>e1dd92b1-366a-42ab-ac01-f5bfe7f0ab4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company_name2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company_name2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b47404eb-cc4a-42e2-8c84-36224d2ed4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e55b86a2-1f3c-4ed5-92bd-2346469db694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d1a32b5-2818-4b1d-8794-e9568810a231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control english_only_space</value>
      <webElementGuid>925be469-546c-40cc-abe7-1b19d231f2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company_name2</value>
      <webElementGuid>7d5d29e8-7a57-439f-aedf-75ed2b6c6c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>company name line 1</value>
      <webElementGuid>cf011b06-e4b1-463f-9caa-8e722e506957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company_name2&quot;)</value>
      <webElementGuid>339ad5d3-96fd-40a6-ba7a-19d88fcf3b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company_name2']</value>
      <webElementGuid>be57735f-e8ad-482a-a4f8-58327650979e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_details_form']/div[2]/div[2]/input</value>
      <webElementGuid>d78571f7-d250-4f49-adb0-91ef87d6ffed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>944ee1ed-d5f9-4c80-9972-9cefc922139d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'company_name2' and @title = 'company name line 1']</value>
      <webElementGuid>4ffa05b5-7745-49b3-962d-10ea7fdd8d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
