<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company NameDepartment_company_name1</name>
   <tag></tag>
   <elementGuidId>88435d8d-8706-4e81-ad46-62c7955c0b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company_name1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company_name1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49e264b0-6369-4490-a782-0b0fd2c4a9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45ac9a2a-4fe1-4cfc-82b9-c237690b4430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c0824b7-ce4a-469a-997f-c457c8faf46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control english_only_space</value>
      <webElementGuid>f230cbc0-6867-4eb5-bc7b-36416382fd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company_name1</value>
      <webElementGuid>b511fb61-2eb3-4b57-b9e2-c2b6443aa1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>company name line 2</value>
      <webElementGuid>7f6ffa02-fb54-443a-b7e1-8bbd288cd6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company_name1&quot;)</value>
      <webElementGuid>2f4aed38-83de-43d4-97e3-d1348ccdeed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company_name1']</value>
      <webElementGuid>8dcce18c-fab2-430e-b036-f2cfb3a12e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_details_form']/div[2]/div[2]/input[2]</value>
      <webElementGuid>5d08a1ae-6646-4701-90fb-5e6c0e6ca9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>8e7d41cc-2567-45be-b548-2bb7f11311ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'company_name1' and @title = 'company name line 2']</value>
      <webElementGuid>a26eba89-2d97-4049-ae38-59259045a2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
