<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country Code_country_code1</name>
   <tag></tag>
   <elementGuidId>842ecbc3-68ad-4c32-ab14-e30b7d93aef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#country_code1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='country_code1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>429de1d5-47d0-44cd-872c-2be40f7a1219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09daa2ae-5119-4f42-864e-4bf0feb2f507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c2330ccf-fa5a-47d1-b3fb-c89eaf577c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number_only</value>
      <webElementGuid>0c74f5ae-a75f-4c3f-bd84-d30321663ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>country_code1</value>
      <webElementGuid>3c457038-db95-4f42-bb9a-d45852cd3058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>country code</value>
      <webElementGuid>1d3df233-13e0-4ed5-88da-4fe58b961aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country_code1&quot;)</value>
      <webElementGuid>53a76032-1258-4f8d-bb88-1bb067c90b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='country_code1']</value>
      <webElementGuid>b0fed7f1-02f1-4842-aaad-cd7a52564fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='phone_info_form']/div[2]/div[2]/input</value>
      <webElementGuid>d17201bf-f8ed-4c2f-867b-261d4a18aa42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[2]/div[2]/input</value>
      <webElementGuid>41ebc1c2-ef60-4a9a-85d4-b52297ce4c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'country_code1' and @title = 'country code']</value>
      <webElementGuid>f163e8bf-b8bb-427a-941c-e086bd8b061d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
