<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PIN_pin</name>
   <tag></tag>
   <elementGuidId>3b21ff24-7d99-45f7-ae43-25d06af1be79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ddde1c8-dda3-40ea-a917-7054c213a27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ca83839e-adf6-4285-be41-9b42c3f8f104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0ba0f02-ebfe-48c9-bb60-e199759feefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control english_only</value>
      <webElementGuid>634af5bc-eb1c-475e-ab98-c87ef63b3229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin</value>
      <webElementGuid>c549704a-1eff-4def-a535-4677236e662f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>pin</value>
      <webElementGuid>b8c3827b-b061-42a1-a004-2cb274100f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin&quot;)</value>
      <webElementGuid>66ba21dd-5f9e-4cf6-8f90-88e30e6bac9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pin']</value>
      <webElementGuid>40937cef-f875-4c0e-a696-50a750656d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credentials_form']/div/div/input</value>
      <webElementGuid>b6aabaef-955f-406f-943a-683858c3ca80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div/input</value>
      <webElementGuid>ece77508-faf0-4046-a7ae-58ec3f8f1944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'textbox' and @id = 'pin' and @title = 'pin']</value>
      <webElementGuid>75e403a7-3d16-4222-bfa5-a9e0528eb0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
