<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Email Address_confirm_email</name>
   <tag></tag>
   <elementGuidId>481f6723-d055-429a-a622-84584ce37913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>422ae644-ca74-4ef3-a005-3e574908bed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0689f866-eb87-43fe-bdd5-578af6f16e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9fb9650-33d9-45ce-9f55-3a8d515e9bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cde038b6-136c-432e-b6e8-8babd23c9fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_email</value>
      <webElementGuid>f41505f8-2df1-4880-8c89-8244979be3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>confirm email</value>
      <webElementGuid>e90c8430-1f3f-4bb5-8e1d-56ca42393f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_email&quot;)</value>
      <webElementGuid>643f68e9-06a6-4759-b03e-37c14b7788b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_email']</value>
      <webElementGuid>8e359acf-5c61-437d-b474-6a77a40a5bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='email_info_form']/div/div[2]/input</value>
      <webElementGuid>1cdae187-0887-4c8a-bd5f-2195a2c55751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div[2]/input</value>
      <webElementGuid>314ea4b6-0d39-4f83-ba3f-210468d344a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'textbox' and @id = 'confirm_email' and @title = 'confirm email']</value>
      <webElementGuid>257ff3eb-b3d7-4edc-8c4f-fefd8b449c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
