<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I agree to receive News, and promotio_6d6b5d_1</name>
   <tag></tag>
   <elementGuidId>b7b6be3d-0891-4169-a71e-a0918f3039b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > input[name=&quot;delivery&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='delivery'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b96b9fbd-dc19-40ad-b875-2f66456099df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f1097eb4-6aa9-4534-a4a0-aec3647544d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SP</value>
      <webElementGuid>ec66bd47-d77d-4281-ba57-5639757857fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delivery</value>
      <webElementGuid>8cf5d91c-5954-4b1d-9bbf-ebe19d9dcc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery</value>
      <webElementGuid>6b72054f-ca46-4f52-8441-53b0784cb238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>I agree to receive News, and promotional offers from partners and associated third parties of Royal Orchid Plus and THAI</value>
      <webElementGuid>3758d6b2-9676-45ac-8fa0-ecc5c1b7d6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_info_form&quot;)/div[@class=&quot;row&quot;]/div[3]/input[@class=&quot;delivery&quot;]</value>
      <webElementGuid>b1ecbb29-0828-4155-bd7b-7a2dfab80e60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='delivery'])[2]</value>
      <webElementGuid>1b88b623-a546-4356-985a-e434c6a4f67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='email_info_form']/div[2]/div[3]/input</value>
      <webElementGuid>b6e081b7-ccef-49d9-a6ec-b40668f23423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>35a0bd0e-2e1e-42f4-8b28-5874cd5a69a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'delivery' and @title = 'I agree to receive News, and promotional offers from partners and associated third parties of Royal Orchid Plus and THAI']</value>
      <webElementGuid>6265305c-c600-4c77-b74e-a6599592eff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
