<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Extension_extension1</name>
   <tag></tag>
   <elementGuidId>03d11a5d-f165-486c-916e-3dca676d2360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#extension1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='extension1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>774105d8-7174-4dfc-b2dc-b8f6af95e396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23d18735-533e-486d-a1f4-81f23557ce95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f750eec4-31f6-40aa-a411-dfc396923ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number_only</value>
      <webElementGuid>982a9abc-7606-4fe1-a169-b8cd3b8b1116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>extension1</value>
      <webElementGuid>5f7e0952-a824-4d85-8f34-9e8e3b88232c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>extension</value>
      <webElementGuid>ed55c8bf-5446-404a-a872-abf3d329033f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extension1&quot;)</value>
      <webElementGuid>34f24305-919b-4771-b56e-e628d9abdf15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='extension1']</value>
      <webElementGuid>b6a58c19-4e3c-4da9-bee5-76eecf141bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='phone_info_form']/div[2]/div[5]/input</value>
      <webElementGuid>bba14307-3752-496c-a7a5-1e5584ad0ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>20df8e72-71a1-4118-a9dd-c70981e6d42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'extension1' and @title = 'extension']</value>
      <webElementGuid>d09f2def-249e-42c1-8bb3-f214ac008a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
