<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Area Code_area_code1</name>
   <tag></tag>
   <elementGuidId>9e9ff540-71c5-45b2-ade5-8becd1fa4808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#area_code1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='area_code1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab595f7b-3263-4026-b64f-cba40e8e6ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f967da6a-5015-4f12-9324-4c80b3b2b4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a87dc0c9-90cf-450a-8cf6-cfb29c4d6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control number_only</value>
      <webElementGuid>183f33e5-d82b-43b5-b008-a2da666dcb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>area_code1</value>
      <webElementGuid>81cc8d7b-69bb-4816-a5c0-013ea117ef12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>area code</value>
      <webElementGuid>43d0bfdc-e7a9-4be9-9cdb-1e2e2f97ec26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;area_code1&quot;)</value>
      <webElementGuid>189dd52a-8227-48de-9eb7-76d6bd39bcab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='area_code1']</value>
      <webElementGuid>97497ed2-5353-440e-8d0c-8c57199bf3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='phone_info_form']/div[2]/div[3]/input</value>
      <webElementGuid>200f4023-eee8-49a8-86ed-51c18757daa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[2]/div[3]/input</value>
      <webElementGuid>a3e903ce-ec91-4a1e-9d7a-016e72839aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'area_code1' and @title = 'area code']</value>
      <webElementGuid>aff3e1b5-f589-4007-8e2e-1ebfb4f64682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
