<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal Code_postalcode</name>
   <tag></tag>
   <elementGuidId>89766900-1eab-4dc0-9893-050db75be99e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#post_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='post_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24ae85ee-4d71-4f44-92ce-50cd29f86b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a0fd3a3b-8f4a-4e0d-b280-d52e25259e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postalcode</value>
      <webElementGuid>676920ad-e192-4de0-a8ba-3e0ce6388885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>postal code</value>
      <webElementGuid>597403bb-705d-4ffd-b45c-cce5d2fdbc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0ed3b0e6-3dc7-4490-8cff-28bcb109d9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>post_code</value>
      <webElementGuid>38665cb2-04da-4374-a7fa-b84f40560deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post_code&quot;)</value>
      <webElementGuid>c865c634-8c1c-4bff-9e09-afdeddfd49f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='post_code']</value>
      <webElementGuid>c3c9d206-7448-4a32-bc0d-6c9a5a616202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_details_form']/div[5]/div[2]/input</value>
      <webElementGuid>fad7fd31-11b9-4af0-8dd5-d5bece8d76a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>5910dee8-2d67-49e8-95b5-62ae6ff25e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'textbox' and @name = 'postalcode' and @title = 'postal code' and @id = 'post_code']</value>
      <webElementGuid>d1021129-3307-4be8-96b6-dc1a50420022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
