<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_English                        Thai</name>
   <tag></tag>
   <elementGuidId>dadc27a0-2d2e-4d14-87d5-7c45f454ab6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#language_pref</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='language_pref']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>45025f5d-8e8a-4983-8549-270c48a04f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f9c8c6c3-596a-4d41-b6cd-c3cba6bbd07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea8012c4-41bd-4065-8e00-49c1f7870358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>language_pref</value>
      <webElementGuid>c58433df-34fc-4e74-8e2a-0f1bf1c3be6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>select language preferences</value>
      <webElementGuid>d7ba088c-a364-4d56-95f9-0a23bc298439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  
                        English
                        Thai
                      </value>
      <webElementGuid>c637121a-394e-41e0-a301-385fc444fa61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;language_pref&quot;)</value>
      <webElementGuid>162b935a-03e5-4597-86d9-e4391a7b0a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='language_pref']</value>
      <webElementGuid>591a60ac-a58d-4e6c-818e-3e658ffe24d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rop-app']/div/div/div/div[2]/div/div/form[2]/div/div/select</value>
      <webElementGuid>d3bc8b69-9786-483c-8f6c-7ca0fc355d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication Preferences'])[1]/following::select[1]</value>
      <webElementGuid>378bbfb4-70aa-4e07-b3f7-006348e4ee61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Credentials'])[1]/preceding::select[1]</value>
      <webElementGuid>d7c61611-af4b-4848-9e83-38e485d2d55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/select</value>
      <webElementGuid>36c53045-9c34-4958-b5ee-6ab4109b4b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'language_pref' and @title = 'select language preferences' and (text() = '  
                        English
                        Thai
                      ' or . = '  
                        English
                        Thai
                      ')]</value>
      <webElementGuid>a1a9ba6d-d0b6-4d6e-8113-320dc033f7a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
