<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select cityPrachinburiAmnajch_4b05c9</name>
   <tag></tag>
   <elementGuidId>7e17ab13-a917-4331-882a-fe974de25719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>52a56af9-9985-41d3-b45c-e022afe5f8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>c2c09493-68f0-438f-9e34-1df828208dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>40f7d3f7-df59-43a6-bb3f-f13e58c5b57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c16fe85-cb7a-4922-b3c6-7ee960255f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ba022f3-4493-4631-9647-00c4be4c3674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>city province</value>
      <webElementGuid>022fc9a3-b2bf-404c-a279-a4e9f9dec70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select cityPrachinburiAmnajcharoenPhayaoBan mak khaengBurirumBangkokChiangraiChainatChumphonChiangmaiChonburiChanthaburiChachoengsaoPhangngaHat yaiMae hong sornPhuketNakhon nayokPichitChaiyaphumKrabiKanchanaburiKamphangsaenKamphaeng phetPrachuap khiri khanKhon kaenKalasinSamut sakhonNakhon phanomSamut songkhramLoeiLopburiLampangMukdahanMaha sarakhamNakhon rajseemaNarathiwatNonthaburiAngthongNanNakhon pathomNongbualampooNakhon sri thammaratNakhon sawanLampoonPattaniPetchaburiPhitsanulokPhetchabunPathum thaniPhraePhatthalungSurinNongkhaiRatchaburiRoi etSrakaewRayongSingburiSongkhlaSi sa ketSamut prakarnSakon nakhonSatunSuphanburiSaraburiTratSukhothaiTakTrangUbon ratchathaniBueng kanAyuthayaUthai thaniRanongSurat thaniUdon thaniUttaraditYalaYasothonOther</value>
      <webElementGuid>a7e04ba3-5abf-4885-8e8e-be4979525680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>4691ea2e-3429-4240-ba2e-98c4e77ed1d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>202eb9d8-e3f3-4455-86ac-10a095d5fe01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact_details_form']/div[4]/div[2]/select</value>
      <webElementGuid>8ca81dbd-a3b3-46a8-959a-3389c856bee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>59f25668-5543-4743-81ef-474d540bbf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'city' and @id = 'city' and @title = 'city province' and (text() = 'Please select cityPrachinburiAmnajcharoenPhayaoBan mak khaengBurirumBangkokChiangraiChainatChumphonChiangmaiChonburiChanthaburiChachoengsaoPhangngaHat yaiMae hong sornPhuketNakhon nayokPichitChaiyaphumKrabiKanchanaburiKamphangsaenKamphaeng phetPrachuap khiri khanKhon kaenKalasinSamut sakhonNakhon phanomSamut songkhramLoeiLopburiLampangMukdahanMaha sarakhamNakhon rajseemaNarathiwatNonthaburiAngthongNanNakhon pathomNongbualampooNakhon sri thammaratNakhon sawanLampoonPattaniPetchaburiPhitsanulokPhetchabunPathum thaniPhraePhatthalungSurinNongkhaiRatchaburiRoi etSrakaewRayongSingburiSongkhlaSi sa ketSamut prakarnSakon nakhonSatunSuphanburiSaraburiTratSukhothaiTakTrangUbon ratchathaniBueng kanAyuthayaUthai thaniRanongSurat thaniUdon thaniUttaraditYalaYasothonOther' or . = 'Please select cityPrachinburiAmnajcharoenPhayaoBan mak khaengBurirumBangkokChiangraiChainatChumphonChiangmaiChonburiChanthaburiChachoengsaoPhangngaHat yaiMae hong sornPhuketNakhon nayokPichitChaiyaphumKrabiKanchanaburiKamphangsaenKamphaeng phetPrachuap khiri khanKhon kaenKalasinSamut sakhonNakhon phanomSamut songkhramLoeiLopburiLampangMukdahanMaha sarakhamNakhon rajseemaNarathiwatNonthaburiAngthongNanNakhon pathomNongbualampooNakhon sri thammaratNakhon sawanLampoonPattaniPetchaburiPhitsanulokPhetchabunPathum thaniPhraePhatthalungSurinNongkhaiRatchaburiRoi etSrakaewRayongSingburiSongkhlaSi sa ketSamut prakarnSakon nakhonSatunSuphanburiSaraburiTratSukhothaiTakTrangUbon ratchathaniBueng kanAyuthayaUthai thaniRanongSurat thaniUdon thaniUttaraditYalaYasothonOther')]</value>
      <webElementGuid>40d537f0-f29a-464d-84a6-5ba30a7dfa9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
