<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--select--                          _bfbc23</name>
   <tag></tag>
   <elementGuidId>cf483939-1a97-41b8-879e-0f257530d0fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='phone1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3e03c262-49ab-4b78-9542-f6aaa85f3cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phonetype</value>
      <webElementGuid>4698de51-7a9d-4ad3-a8a8-4af2fc6d9084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5a19014-a340-4e7b-a548-3dc81442fa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>876933a3-02b0-48c6-876e-442bcb758971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone1</value>
      <webElementGuid>20f11d5f-ae7e-408f-a903-191b6fc6e29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>phone type</value>
      <webElementGuid>c09031ab-ffd2-4332-8f9a-5f027aa694df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                          --select--
                          Home
                          Business
                          Mobile
                          Fax
                        </value>
      <webElementGuid>7324ca35-c5ae-4b8a-98d9-76686814e83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone1&quot;)</value>
      <webElementGuid>67887383-729a-42f4-a979-68a083a9bc31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='phone1']</value>
      <webElementGuid>b5d6f5ad-9e37-4734-99e9-5934600f5058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='phone_info_form']/div[2]/div/select</value>
      <webElementGuid>6342ccc2-508d-4b00-96ce-27d0499c8893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>994c313d-1ac1-44ee-8050-3a3e8550cd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'phonetype' and @id = 'phone1' and @title = 'phone type' and (text() = '
                          --select--
                          Home
                          Business
                          Mobile
                          Fax
                        ' or . = '
                          --select--
                          Home
                          Business
                          Mobile
                          Fax
                        ')]</value>
      <webElementGuid>9eb9dfa8-bcfb-4b77-a70b-7847b7a6459d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
